### ISSUE TITLE
라이엇 게임즈 API Personal Key 발급

### ISSUE THREAD

**Issue by mangodm-web** [TFTrashaimase/tft-victory-planner#18]
### closed this as not planned?
Riot에서 허가를 안 해줌

## 요약
현재 사용 중인 Development API Key는 24시간마다 수동 갱신이 필요하여, 만료되지 않는 Personal API Key를 발급 받고자 합니다. 

---

## TODO
- [x] 빠른 승인 심사를 위해 [데모 앱](https://scratch-one-phi.vercel.app/) 준비
- [x] Personal API Key 신청서 작성
- [ ] Key 발급 승인 후 팀원들에게 공유

---

## NOTES
- 키 발급 요청 제한으로 인해 공용 지메일 계정이 아닌 개인 계정으로 신청했습니다. 계정 정보는 슬랙 채널을 통해 공유할 예정입니다!
- 데모 앱 코드는 [별도의 저장소](https://github.com/TFTrashaimase/scratch)에 추가해두었습니다.
